general:
  vulnerabilities:
    - CVE-2022-23852  
    - CVE-2022-23990  
#     - CVE-2019-20477
#     - CVE-2020-14343
#     - CVE-2020-1747 
  bestPracticeViolations:
#    - CIS-DI-0005
#    - DKL-LI-0003
#    - CIS-DI-0006
#    - DKL-DI-0006
