# This VirtualHost is autogenerated by the container startup script
<VirtualHost *:9090>
    ServerName {{ .Env.METRICS_VHOST_SERVER_NAME }}
    ServerAlias *
    LimitRequestLine 16384

    <FilesMatch \.php$>
      SetHandler "proxy:unix:/app/var/run/php-fpm/php-fpm.sock|fcgi://localhost/"
    </FilesMatch>

    DocumentRoot {{ .Env.APP_SRC_DIR }}/public
    <Directory {{ .Env.APP_SRC_DIR }}/public >
      AllowOverride None
      Order Allow,Deny
      Allow from All
      Require all granted
      FallbackResource /index.php
    </Directory>

    <Directory {{ .Env.APP_SRC_DIR }}/public/bundles>
        FallbackResource disabled
    </Directory>

    RewriteEngine On
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    IncludeOptional /app/etc/apache2/conf.d/__metrics.env

</VirtualHost>